### ISSUE TITLE
Development Roadmap (2025 S1)

### ISSUE THREAD

**Issue by huangyz0918** [MLSysOps/MLE-agent#264]
For anyone who wants to contribute (add features, report bugs, or just simply discuss and learn), join our [Discord](https://discord.gg/d9vcY7PA8Z) 👋 
Or you can just comment here for open discussions! 👨‍💻 

### RAG Module for Code Indexing

- [x] Complete a PoC with LanceDB by implementing a memory.py file. #262  @leeeizhang 
- [x] Build a pipeline to generate embeddings for local code RAG.  #259 #265  @huangyz0918 
- [ ] Enable storing the "successfully" project (generated code, plan, suggestions, and settings), for RAG and enhancement.
- [x] Add a CLI entry for managing memory (list embedded files, allow CRUD). @leeeizhang #266 #270 

#### Research Topic 

FYI @HuaizhengZhang 

- [ ] PoC: How to sync up the knowledge updating (e.g., the code will update frequently)
- [ ] PoC: How to efficiently scan the file as memory? (the embedding costs time, for a large amount of codebase/files)
- [ ] PoC: How to do the chunking for code different types of textual (image/audio, other modality) data
- [ ] PoC: Using [graphRAG](https://github.com/microsoft/graphrag) for overall (code) information summarization

### Enhance `mle chat` 

- [ ] Improved the `mle chat`'s agent calling, allow calling agents (now we can call functions) #260 @YuanmingLeee 

### Prompting

- [ ] Integrated the reference code search to Advisor/Debugger/Coder
- [ ] Add tracking tool, with integration to [Langfuse](https://langfuse.com/) or other tools. Set the default tracking to `False`, or letting users know while first run the `mle` in the terminal about usage tracking. https://github.com/MLSysOps/MLE-agent/issues/255

### Other LLM Framework Support

- [ ] Integrate with the Ollama backend. (Ollama is added, test and make it better) -- local
- [ ] Integrate with vLLM backend -> vLLM cloud backend -- on-prem

### Function Calls

- [ ] Add local logging of tool/function calling.
- [ ] Added functions to preview multi-modality data, start with the image data.
- [ ] Function store: #268 
- [ ] Added support for local LLMs (tested the APIs with [vLLM](https://github.com/vllm-project/vllm)), disable the function calling without errors if the LLM doesn't support.  https://github.com/MLSysOps/MLE-agent/issues/227

### Documentation

- [ ] Updated the doc site with new release/features @huangyz0918 @leeeizhang 
- [ ] New demo video on in the README.md @HuaizhengZhang

**Comment by huangyz0918** [comment]
@TimeLordRaps Do you mean this https://github.com/gusye1234/nano-graphrag?

I think it is an elegant, small, and clean implementation of GraphRAG. However, to implement GraphRAG, a graph-based data store and (usually) a KV store must be introduced, which brings problems in 1) extract storage/dependency and 2) compatibility with other stores. Moreover, I am not sure how such graph-based indexing performs on code generation tasks. 

But I think it is worth trying in the `chat mode` for our project -- since the user may ask very high-level, or summarized questions based on the large code base. For the `advisor` it can also help, but the very first problem is how we handle the function call with the graph search (maybe use graph query for project summarization as the pre-retrieval before calling function like web search).

**Comment by TimeLordRaps** [comment]
https://github.com/CEDARScript/cedarscript-grammar This should help. A friend of mines project I'm helping work forward into an eventual shared resource of personified coding graphs. Ie think aiders --edit-format, which is where its currently being applied, that said, we were just discussing branching out to other coding frameworks.
